services:
  mcp:
    environment:
      - PROVIDER=OLLAMA
      - MODEL_BASE_URL=http://ollama:11434
      - MODEL_NAME=llama3.1:8b
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    # gpus: all  #  NVIDIA Container Toolkit need to be installed on the host to be able to use GPUs

volumes:
  ollama-data: